Support daemon user
* Bug Fix: Recreate default wildfly.sasl.local-user.challenge-path location ...
    For some reason the default SASL challenge location results in following exception if JBOSS-LOCAL-USER is
    attempted as any user other than root:

      TRACE [org.jboss.remoting.remote.server] (default task-59) Server sending authentication rejected:
        javax.security.sasl.SaslException: Failed to create challenge file [Caused by java.io.IOException:
        Permission denied]
      at org.jboss.sasl.localuser.LocalUserServer$2.evaluateMessage(LocalUserServer.java:139)

    It is suspected that the tar is preserving ACLs or SELinux attributes; however, attempts to remove them with
    --no-acls, --no-selinux, and --no-xattrs has no effect!?!
* Bug Fix: Execute add-user as wildfly.